version: "3"
services:
  app:
    container_name: AppServer
    build: ./APP_SERVER
    restart: always
    ports:
      - "7777:7777"
    networks:
      - tpnet

  data_server:
    container_name: ApiServer
    build: ./API_SERVER
    restart: always
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/PGDRE
    ports:
      - "7779:7779"
    depends_on:
      - mongodb
    networks:
      - tpnet

  mongodb:
    container_name: MongoDB
    image: mongo
    restart: always
    ports:
      - '27018:27017'
    volumes:
      - tpData:/data/db
    networks:
      - tpnet

  auth_server:
    container_name: AuthServer
    build: ./AUTH_SERVER
    restart: always
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/PGDRE
    ports:
      - "7778:7778"
    depends_on:
      - mongodb
    networks:
      - tpnet
      
networks:
  tpnet:
    name: tpnet
    driver: bridge
volumes:
  tpData: